using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace BytexDigital.RGSM.Shared
{
    public class ArgumentsHelper
    {
        public static Task<List<string>> GetArgumentsListAsync(string argumentsString, CancellationToken cancellationToken = default)
        {
            // Read additional custom arguments in a manner so we can better merge them with autogenerated arguments
            List<string> arguments = new List<string>();

            StringBuilder argumentBuilder = new StringBuilder();
            bool interpretSpaceAsLiteral = false;

            foreach (var character in argumentsString)
            {
                if (character == '"')
                {
                    interpretSpaceAsLiteral = !interpretSpaceAsLiteral;
                    continue;
                }

                if (character == ' ' && !interpretSpaceAsLiteral)
                {
                    arguments.Add(argumentBuilder.ToString());
                    argumentBuilder = new StringBuilder();
                    continue;
                }

                argumentBuilder.Append(character);
            }

            arguments.Add(argumentBuilder.ToString());

            return Task.FromResult(arguments);
        }
    }
}
